### ISSUE TITLE
麻烦兼容一下CentOS 6

### ISSUE THREAD

**Issue by Scyllaly** [hao-hao-hao/Others#1]
因为CentOS 6 下午是没有systemctl滴。。这货只有centos7下才有。项目已经给你挂到ssrpanel里的wiki啦，我准备把它放到ssrpanel项目里作为节点添加引导

**Comment by Scyllaly** [comment]
我去，我看了代码，整个就是以CentOS 7为标准的啊，能不能搞个CentOS 6的版本滴，谢谢啦

**Comment by hao-hao-hao** [comment]
我这个是随便做的，bbr那个是直接run别人的脚本，写在了readme里面。 centos 6默认用的是什么？

**Comment by hao-hao-hao** [comment]
你要不要把这个直接放在你的github里面，我放在这只是为了方便我下载而已，你放到你那你有空可以进行更新一下。

**Comment by Scyllaly** [comment]
@Hao-Luo 要啊，我要放到项目里。先fork一份到我git里，让更多人看到，来star
哈哈哈

**Comment by Scyllaly** [comment]
@Hao-Luo 确实超好用

**Comment by Scyllaly** [comment]
@Hao-Luo 
CentOS 6.X下会酱紫

 mysql-server address:127.0.0.1
 mysql-server username:root
 mysql-server password:root
 ssr node id:1
setting up the ssr as service in systemd
cp: cannot create regular file `/etc/systemd/system/ssr.service': No such file or directory
./deploy_ssr.sh: line 19: systemctl: command not found
./deploy_ssr.sh: line 20: systemctl: command not found
./deploy_ssr.sh: line 21: systemctl: command not found
SSR Service is installed

**Comment by Scyllaly** [comment]
@Hao-Luo 我把你这个脚本小改动了下，放到项目里了，在server/deploy.sh

**Comment by hao-hao-hao** [comment]
好的谢谢  :_)  wiki不用写作者是我了，这个就是一点小脚本，你把bbr脚本的作者备注一下吧。
